# font_atlas.ph — GENERATED by pstudio/tools/mkatlas.c (see font_atlas.p).
# 7 mono grids, one per zoom step: every step is a REAL rasterization
# of the font, not a pixel-doubled bitmap. Sizes (px): 11 13 15 17 20 24 29.
# Glyphs: ASCII 32..126, Latin-1 160..255 (accents), typographic
# punctuation and U+25A1 last; fa_index(cp) gives the index and
# fa_pixels(size) the grid (8-bit alpha, glyph i at i*cw*ch).

def fa_sizes() -> i32                     # how many zoom steps exist
def fa_cell_w(size: i32) -> i32
def fa_cell_h(size: i32) -> i32
def fa_baseline(size: i32) -> i32
def fa_px(size: i32) -> i32               # nominal pixel height
def fa_count() -> i32
def fa_index(cp: u32) -> i32
def fa_pixels(size: i32) -> const *u8
