# font_atlas.p — GENERATED by pstudio/tools/mkatlas.c (JetBrains Mono,
# OFL). DO NOT EDIT; regenerate with:
#   cc pstudio/tools/mkatlas.c -o mkatlas -lm && ./mkatlas <ttf> \
#      pstudio/font_atlas.p pstudio/font_atlas.ph [px...]
# 7 mono grids (one per zoom step, each a REAL rasterization), 209
# glyphs each: ASCII 32..126, Latin-1 160..255, 17 punctuation extras and
# U+25A1 last. Inside a grid, glyph i starts at i*cell_w*cell_h.
import "font_atlas.ph"

# The 263 549 bytes of the seven grids, EMBEDDED (63.5): the file is the data,
# read at compile time and emitted as a static array, so the editor still ships
# as one binary and this source is a page instead of eleven thousand lines.
# Regenerating the atlas rewrites font_atlas.bin; nothing here changes.
fa_data: const u8[] = embed_bytes("font_atlas.bin")

fa_cw: const i32[7] = {6, 6, 7, 8, 10, 11, 14}
fa_ch: const i32[7] = {12, 13, 15, 17, 20, 24, 29}
fa_bl: const i32[7] = {9, 10, 12, 13, 15, 19, 22}
fa_off: const usize[7] = {0, 15048, 31350, 53295, 81719, 123519, 178695}
fa_px_tbl: const i32[7] = {11, 13, 15, 17, 20, 24, 29}

def fa_sizes() -> i32:
    return 7

def fa_cell_w(size: i32) -> i32:
    return fa_cw[size]

def fa_cell_h(size: i32) -> i32:
    return fa_ch[size]

def fa_baseline(size: i32) -> i32:
    return fa_bl[size]

def fa_px(size: i32) -> i32:
    return fa_px_tbl[size]

def fa_count() -> i32:
    return 209

# codepoint -> index inside a grid; outside the ranges it is the box
def fa_index(cp: u32) -> i32:
    if cp >= 32 and cp <= 126:
        return i32(cp) - 32
    if cp >= 160 and cp <= 255:
        return 95 + i32(cp) - 160
    if cp == 8211:
        return 191
    if cp == 8212:
        return 192
    if cp == 8216:
        return 193
    if cp == 8217:
        return 194
    if cp == 8220:
        return 195
    if cp == 8221:
        return 196
    if cp == 8226:
        return 197
    if cp == 8230:
        return 198
    if cp == 8592:
        return 199
    if cp == 8594:
        return 200
    if cp == 10003:
        return 201
    if cp == 10007:
        return 202
    if cp == 9656:
        return 203
    if cp == 9662:
        return 204
    if cp == 9679:
        return 205
    if cp == 9670:
        return 206
    if cp == 9642:
        return 207
    return 208

def fa_pixels(size: i32) -> const *u8:
    return fa_data + fa_off[size]
