# icons.p — GENERATED by pstudio/tools/mkicons.c from the SVGs in
# pstudio/icons/ (Lucide, ISC). DO NOT EDIT; regenerate with:
#   cc pstudio/tools/mkicons.c -o mkicons -lm && ./mkicons \
#      pstudio/icons.p pstudio/icons.ph pstudio/icon_ids.psc pstudio/icons/*.svg
# 50 icons in 7 square sheets, one per zoom step, each a REAL
# rasterization of the vector at that size. 8-bit alpha, tinted by a
# theme role at draw time exactly like a glyph: icon i of the sheet for
# `size` starts at i*px*px.
import "icons.ph"

# The 139800 bytes of the sheets, EMBEDDED: the file is the data, read at
# compile time, so the editor still ships as a single binary.
ico_data: const u8[] = embed_bytes("icons.bin")

ico_px_tbl: const i32[7] = {12, 14, 16, 18, 20, 24, 30}
ico_off: const usize[7] = {0, 7200, 17000, 29800, 46000, 66000, 94800}

def ico_sizes() -> i32:
    return 7

def ico_px(size: i32) -> i32:
    return ico_px_tbl[size]

def ico_count() -> i32:
    return 50

def ico_pixels(size: i32) -> const *u8:
    return ico_data + ico_off[size]
