# icons.ph — GENERATED by pstudio/tools/mkicons.c (see icons.p).
# 50 icons x 7 zoom steps of 8-bit alpha. Sizes (px): 12 14 16 18 20 24 30.
# The ids are in pstudio/icon_ids.psc, generated beside this.

def ico_sizes() -> i32                    # how many zoom steps exist
def ico_px(size: i32) -> i32              # the side of a square icon
def ico_count() -> i32
def ico_pixels(size: i32) -> const *u8    # icon i at i*px*px
