"""The icon ids — GENERATED by pstudio/tools/mkicons.c. DO NOT EDIT.

One `const` per SVG in pstudio/icons/, numbered by SORTED NAME — so
adding an icon renumbers every icon after it. That is exactly why these
are names and never literals: `ICO_PLAY` is whatever the generator
decided this time, and this file is the only thing that has to agree
with the sheet. `ICO_NONE` is a row with no icon at all.

The pixels live on the P side (`pstudio/icons.p`, embedded) because that
is where the rasterizer that paints them lives.
"""

const ICO_NONE: int = -1

const ICO_ARROW_LEFT: int = 0
const ICO_ARROW_RIGHT: int = 1
const ICO_BOOKMARK: int = 2
const ICO_BOX: int = 3
const ICO_BRACES: int = 4
const ICO_BUG: int = 5
const ICO_CHECK: int = 6
const ICO_CHEVRON_DOWN: int = 7
const ICO_CHEVRON_LEFT: int = 8
const ICO_CHEVRON_RIGHT: int = 9
const ICO_CHEVRON_UP: int = 10
const ICO_CIRCLE_ALERT: int = 11
const ICO_CIRCLE_CHECK: int = 12
const ICO_CIRCLE_DOT: int = 13
const ICO_CIRCLE_X: int = 14
const ICO_COPY: int = 15
const ICO_CORNER_DOWN_LEFT: int = 16
const ICO_FILE_CODE: int = 17
const ICO_FILE: int = 18
const ICO_FLASK_CONICAL: int = 19
const ICO_FOLDER_OPEN: int = 20
const ICO_FOLDER: int = 21
const ICO_GIT_BRANCH: int = 22
const ICO_HAMMER: int = 23
const ICO_HASH: int = 24
const ICO_INFO: int = 25
const ICO_LIST_TREE: int = 26
const ICO_LIST: int = 27
const ICO_MINUS: int = 28
const ICO_MOON: int = 29
const ICO_PACKAGE: int = 30
const ICO_PANEL_BOTTOM: int = 31
const ICO_PANEL_LEFT: int = 32
const ICO_PANEL_RIGHT: int = 33
const ICO_PLAY: int = 34
const ICO_PLUS: int = 35
const ICO_REDO_2: int = 36
const ICO_REFRESH_CW: int = 37
const ICO_SAVE: int = 38
const ICO_SEARCH: int = 39
const ICO_SETTINGS: int = 40
const ICO_SQUARE: int = 41
const ICO_SUN: int = 42
const ICO_TERMINAL: int = 43
const ICO_TRASH_2: int = 44
const ICO_TRIANGLE_ALERT: int = 45
const ICO_TYPE: int = 46
const ICO_UNDO_2: int = 47
const ICO_VARIABLE: int = 48
const ICO_X: int = 49

const ICO_COUNT: int = 50
