# psrt_rt.ph — o que a camada do que roda oferece (tasks, escalonador,
# multiplexador, recv, pool, socket, arquivo, workers, compartilhados).
import "psrt_types.ph"

# Make one and run its first step right away: calling an `async def` starts it.
def ps_task_new(ctx: *PsCtx, step: def(ctx: *PsCtx, t: *PsTask) -> bool, frame: *PsObj) -> *PsTask
def ps_task_done(t: *PsTask) -> bool
def ps_task_step(ctx: *PsCtx, t: *PsTask)
# Park `waiter` on `on`, which is not done yet. The step function returns right
# after calling this, and the scheduler resumes it when `on` finishes.
def ps_task_park(ctx: *PsCtx, waiter: *PsTask, on: *PsTask)
# 79.4: the siblings of `gather` and `race`. `gather_settled` waits for every
# task and hands back the error of each (None where it worked); `first_ok`
# gives the index of the first that SUCCEEDED and cancels the rest.
def ps_gather_settled(ctx: *PsCtx, ts: *PsList) -> *PsList
def ps_gather_settled_task(ctx: *PsCtx, ts: *PsList) -> *PsTask
def ps_first_ok(ctx: *PsCtx, ts: *PsList) -> i64
def ps_first_ok_task(ctx: *PsCtx, ts: *PsList) -> *PsTask
# 79.4: the concurrency limit, in the only shape that can throttle anything —
# over the ITEMS, making at most `at_most` tasks at a time. A limit at `gather`
# time would arrive after every task had already started (35.1's hot start).
def ps_gather_map(ctx: *PsCtx, items: *PsList, mk: def(env: *void, ctx: *PsCtx, ep: const *void) -> *PsTask, env: *void, esize: i32, eref: bool, at_most: i64) -> *PsList
def ps_gather_map_task(ctx: *PsCtx, items: *PsList, mk: def(env: *void, ctx: *PsCtx, ep: const *void) -> *PsTask, env: *void, esize: i32, eref: bool, at_most: i64) -> *PsTask
# From code that is NOT a task (the entry point): run the scheduler until this
# task finishes. It is the only place the runtime ever blocks.
def ps_task_wait(ctx: *PsCtx, t: *PsTask)
# 78.4: an `await` whose value is already there still gives the others a turn —
# the generated step calls this and returns, instead of carrying on.
def ps_task_yield(ctx: *PsCtx, t: *PsTask)
def ps_sched_yield(ctx: *PsCtx) -> bool
# 77.3: run until nothing is ready, no deadline is pending and no I/O is in
# flight. Called once, at the end of the program.
def ps_sched_drain(ctx: *PsCtx)
# the step function calls this when the body raised: the error travels to
# whoever awaits (19.3)
def ps_task_fail(ctx: *PsCtx, t: *PsTask)
def ps_report_lost(ctx: *PsCtx)
# 19.3: at the await, the error the task finished with is raised again
def ps_lost_seen(t: *PsTask)
def ps_task_take_err(ctx: *PsCtx, t: *PsTask)
# where the result of a finished task lives: the frame's first user field, at a
# fixed offset, which is what lets an await read it without knowing which
# function produced it
def ps_task_ret(t: *PsTask) -> *void
# Cancelling is COOPERATIVE and safe by construction: it only acts where the
# task was already going to stop — at its next step — and it acts by RAISING
# there, so every `defer` and every `with` unwinds exactly as it would for any
# other error. A task that never awaits never cancels; that is what workers are
# for (36.4).
def ps_task_cancel(ctx: *PsCtx, t: *PsTask)
def ps_task_cancelled(t: *PsTask) -> bool
# The first of them to finish WINS and the others are cancelled — the idiom
# that leaves no orphan behind. Answers the index of the winner.
# a finished task carrying one number — what `race` and `timeout` answer, so
# that waiting for them is the same `await` every other wait uses (36.2)
# a task the CLOCK finishes: `sleep` and `tick` are made of this (48.2)
def ps_timer_task(ctx: *PsCtx, at: f64) -> *PsTask
# one step of the world: run what is ready, or wait for the next deadline.
# False = nothing could happen, which is a deadlock.
def ps_sched_progress(ctx: *PsCtx) -> bool
def ps_task_of_int(ctx: *PsCtx, v: i64) -> *PsTask
def ps_race(ctx: *PsCtx, ts: *PsList) -> i64
# `race` against the clock: the task wins if it finishes in time, and loses by
# being cancelled. True = it finished, False = the clock did.
def ps_timeout(ctx: *PsCtx, t: *PsTask, seconds: f64) -> bool
# `spawn(f, args)`: the thunk is generated by the compiler — it knows the
# argument struct and the call — and everything thread-shaped is here.
def ps_worker_new(ctx: *PsCtx, entry: def(p: *void) -> *void, args: *void, nargs: usize) -> *PsWorker
# the thunk asks for its own block and its arguments
def ps_worker_args(blk: *void) -> *void
# 34.3's copy ladder, for the one collected thing that can already cross: a
# string leaves as malloc'd BYTES and is rebuilt on the other side, in the other
# heap. No reference spans two heaps, which is the whole rule (18.1).
def ps_str_export(s: *PsStr) -> *char
def ps_str_import(ctx: *PsCtx, p: *char) -> *PsStr
# the same ladder for a list of PURE BYTES (34.3): the elements are copied out
# whole and rebuilt on the other side, in the other heap. A list of references
# would need each of them serialized too, and that is the rung above.
def ps_list_export(l: *PsList) -> *void
def ps_list_import(ctx: *PsCtx, p: *void) -> *PsList
# ... and says it is finished, capturing an error nobody caught (37.4)
def ps_worker_finish(ctx: *PsCtx, blk: *void)
# `parent.send(x)` from inside; `w.send(x)` from outside. Both answer whether
# the message went into the queue (45.3) — never an exception, never silence.
# 107.8: o canal ainda pode entregar? (`w.alive()` do lado do pai,
# `parent.open()` do lado do worker — a mesma pergunta, dos dois lados)
def ps_chan_open(w: *PsWorker) -> bool
def ps_chan_close(w: *PsWorker)
def ps_parent_open(ctx: *PsCtx) -> bool
def ps_worker_send_up(ctx: *PsCtx, p: const *void, size: usize) -> bool
# 34.3, the general case: a message that is not pure bytes is SERIALIZED on the
# way out and rebuilt in the RECEIVER's heap on the way in. That is not an
# optimisation to skip — copying a graph straight across would allocate in
# another thread's heap and set its collector running, which is exactly what
# 18.1 forbids. A `record` and a number still go by memcpy, because they ARE
# bytes (21.1); a string, a list, a dict, a set and a `struct` are graphs and
# go through the shape the compiler wrote for them (74.2).
def ps_send_obj_up(ctx: *PsCtx, sh: const *PsShape, slot: const *void) -> bool
def ps_send_obj_down(w: *PsWorker, sh: const *PsShape, slot: const *void) -> bool
def ps_worker_recv_obj(ctx: *PsCtx, w: *PsWorker, sh: const *PsShape, size: usize) -> *PsTask
def ps_parent_recv_obj(ctx: *PsCtx, sh: const *PsShape, size: usize) -> *PsTask
# what a generated `S__ser` / `S__des` calls, once per field
def ps_ser_value(s: *PsSer, sh: const *PsShape, slot: const *void)
def ps_des_value(ctx: *PsCtx, d: *PsDes, sh: const *PsShape, slot: *void)
def ps_worker_send_down(w: *PsWorker, p: const *void, size: usize) -> bool
# `await w.recv()` / `await parent.recv()`: blocks until a message arrives or
# the other side is gone, and hands back a task that is already finished — the
# shape `await` wants, with the waiting done here.
def ps_worker_recv(ctx: *PsCtx, w: *PsWorker, size: usize) -> *PsTask
def ps_parent_recv(ctx: *PsCtx, size: usize) -> *PsTask
# 37.3: the failure, as the same `Error` a catch binds — message and category —
# rebuilt in the CALLER's heap. None while it runs, and None if it succeeded.
def ps_worker_error(ctx: *PsCtx, w: *PsWorker) -> *PsErr
# 36.3: the program waits for every worker before it ends
def ps_join_all(ctx: *PsCtx)
# `gather(ts)` (35.3): every task, awaited, results in the SAME order the tasks
# were given in — which is the point of it over a loop of awaits.
def ps_gather(ctx: *PsCtx, ts: *PsList, esize: i32, eref: bool) -> *PsList
# the same, wrapped as a finished task so that `await gather(...)` reads like
# every other await
def ps_gather_task(ctx: *PsCtx, ts: *PsList, esize: i32, eref: bool) -> *PsTask
# The program's own surroundings: what it was called with, what the environment
# says, what time it is, and how to stop. `main` hands the arguments over on the
# first line, because nothing else can see them.
def ps_sys_args(argc: int, argv: **char)
def ps_sys_argv(ctx: *PsCtx) -> *PsList
def ps_sys_env(ctx: *PsCtx) -> *PsDict
def ps_sys_exit(ctx: *PsCtx, code: i64)
def ps_math_inf() -> f64
def ps_math_nan() -> f64
# `await sleep(s)` (48.2). Until the I/O loop of 18.4 exists this really sleeps
# the thread: at the TOP LEVEL that is exactly right — the main thread has
# nothing else to do while the workers run — and inside an `async def` it is the
# honest limitation, said out loud.
def ps_sleep(ctx: *PsCtx, seconds: f64) -> *PsTask
# what a worker is doing (37.3), for a parent that supervises
def ps_worker_status(w: *PsWorker) -> i64
# 36.3: mark a worker as one the program will not wait for at the end
def ps_worker_detach(w: *PsWorker)
def ps_file_open(ctx: *PsCtx, path: *PsStr, mode: *PsStr, file: const *char, line: i32) -> *PsFile
# 76.2: the same operations, as TASKS. The call describes the job and gives it
# to the pool; the waiting happens in the scheduler, next to the clock and the
# message queues, so nothing else in this context stops.
def ps_aio_open(ctx: *PsCtx, path: *PsStr, mode: *PsStr) -> *PsTask
def ps_aio_read(ctx: *PsCtx, f: *PsFile, n: i64) -> *PsTask
def ps_aio_readall(ctx: *PsCtx, f: *PsFile, want: i32) -> *PsTask
def ps_aio_write(ctx: *PsCtx, f: *PsFile, s: *PsStr) -> *PsTask
def ps_aio_write_bytes(ctx: *PsCtx, f: *PsFile, l: *PsList) -> *PsTask
def ps_aio_write_bytesobj(ctx: *PsCtx, f: *PsFile, b: *PsBytes) -> *PsTask
def ps_aio_read_into(ctx: *PsCtx, f: *PsFile, b: *PsBuffer, off: i64, n: i64, file: const *char, line: i32) -> *PsTask
def ps_aio_write_from(ctx: *PsCtx, f: *PsFile, b: *PsBuffer, off: i64, n: i64, file: const *char, line: i32) -> *PsTask
def ps_aio_close(ctx: *PsCtx, f: *PsFile) -> *PsTask
# 118: os dois membros de um processo terminado (`os.run`)
def ps_proc_status(p: *PsProc) -> i64
def ps_proc_output(p: *PsProc) -> *PsStr
# liberar um trabalho que nem chegou a ser submetido (o caminho de erro de
# `os.run`, que monta o vetor de argumentos e pode desistir no meio)
def ps_work_free(w: *PsWork)
def ps_work_new(op: i32) -> *PsWork
def ps_pool_submit(ctx: *PsCtx, w: *PsWork)
def ps_io_task(ctx: *PsCtx, w: *PsWork, isref: bool, size: usize) -> *PsTask
def ps_aprint(ctx: *PsCtx, s: *PsStr) -> *PsTask
# `net.listen(port)` gives a server, `await srv.accept()` a connection, and a
# connection reads and writes bytes. socket/bind/listen/setsockopt stay behind
# it, because they are ceremony and not what the program is about.
#
# Accept, recv and send are POLLED: a socket has a real non-blocking mode, so
# the scheduler waits for the descriptor in the `poll` it already runs (74.1)
# and the syscall happens inline when it can no longer block. Connect and DNS
# go to the POOL instead — `getaddrinfo` blocks and cannot be talked out of it.
def ps_net_listen(ctx: *PsCtx, port: i64) -> *PsConn
def ps_net_accept(ctx: *PsCtx, srv: *PsConn) -> *PsTask
def ps_net_connect(ctx: *PsCtx, host: *PsStr, port: i64) -> *PsTask
def ps_net_lookup(ctx: *PsCtx, host: *PsStr) -> *PsTask
def ps_conn_read(ctx: *PsCtx, c: *PsConn, n: i64) -> *PsTask
def ps_conn_write(ctx: *PsCtx, c: *PsConn, s: *PsStr) -> *PsTask
def ps_conn_write_bytes(ctx: *PsCtx, c: *PsConn, l: *PsList) -> *PsTask
# 135.2: the I/O that does not allocate and does not copy — the bytes land in,
# or leave from, memory the caller already had.
def ps_conn_write_bytesobj(ctx: *PsCtx, c: *PsConn, b: *PsBytes) -> *PsTask
def ps_conn_read_into(ctx: *PsCtx, c: *PsConn, b: *PsBuffer, off: i64, n: i64, file: const *char, line: i32) -> *PsTask
# 140/F5: esperar por uma mudança. É a MESMA espera de um socket, porque o
# descritor do inotify é um stream — não é uma segunda maneira de esperar.
def ps_fd_task(ctx: *PsCtx, w: *PsWork, isref: bool, size: usize) -> *PsTask
# ... e uma tarefa que já vem PRONTA, para quando não há nada por que esperar
def ps_msg_task(ctx: *PsCtx, m: *PsMsg, size: usize) -> *PsTask
# 140/F4: a janela de um Buffer, conferida uma vez e num sítio só
def ps_buf_window_pub(ctx: *PsCtx, b: *PsBuffer, off: i64, n: i64, what: const *char, file: const *char, line: i32) -> *char
def ps_conn_write_from(ctx: *PsCtx, c: *PsConn, b: *PsBuffer, off: i64, n: i64, file: const *char, line: i32) -> *PsTask

# ---------- F7: os sockets que faltavam ----------
# UDP: um datagrama não é um fluxo, e a assinatura muda por isso — o que chega
# diz DE ONDE veio, e o que sai leva o destino.
def ps_net_udp(ctx: *PsCtx, port: i64) -> *PsConn
def ps_conn_recv_from(ctx: *PsCtx, c: *PsConn, b: *PsBuffer, off: i64, n: i64, out from: *PsStr, file: const *char, line: i32) -> i64
def ps_conn_send_to(ctx: *PsCtx, c: *PsConn, b: *PsBuffer, off: i64, n: i64, host: *PsStr, port: i64, file: const *char, line: i32) -> i64
# Unix: o mesmo `Socket` sobre um CAMINHO em vez de uma porta
def ps_net_unix_listen(ctx: *PsCtx, p: *PsStr) -> *PsConn
def ps_net_unix(ctx: *PsCtx, p: *PsStr) -> *PsConn
def ps_conn_close(ctx: *PsCtx, c: *PsConn)
# F8: `os.spawn_pty` is a layer up and builds a Conn of its own
def ps_conn_new(ctx: *PsCtx, fd: int, listening: i32) -> *PsConn
def ps_sock_nonblock(fd: int)
def ps_conn_port(c: *PsConn) -> i64
def ps_file_write(ctx: *PsCtx, f: *PsFile, s: *PsStr, file: const *char, line: i32) -> i64
def ps_file_read(ctx: *PsCtx, f: *PsFile, file: const *char, line: i32) -> *PsStr
def ps_file_readlines(ctx: *PsCtx, f: *PsFile, file: const *char, line: i32) -> *PsList
def ps_file_close(ctx: *PsCtx, f: *PsFile)
# The third layer of the model: a global is the worker's own (42.2), a message
# is a transfer (34.3), and a `shared` is synchronized BY COPY — one mutex per
# variable, and a compound operation holds it for the whole read-modify-write,
# so a single operation never races.
#
# The lock is opaque here on purpose: the compiler emits the variables, and all
# it needs from the runtime is somewhere to put a mutex it does not have to
# know the shape of.
# A `shared` variable of type `str` (42.1): the bytes live OUTSIDE every heap,
# in the same PsSStr the shared table uses. Reading builds a fresh string in
# the READER's heap and writing copies the bytes in — the copy ladder, in both
# directions, and the lock is taken here so no caller can forget it.
# the INITIAL value of a shared string, written before any context exists —
# which is why it takes bytes and not a `str`
def ps_shared_str_init(slot: *PsSStr, bytes: const *char, n: i64)
def ps_shared_str_get(ctx: *PsCtx, mu: *void, slot: *PsSStr) -> *PsStr
def ps_shared_str_put(mu: *void, slot: *PsSStr, v: *PsStr)
def ps_lock_new() -> *void
def ps_lock(mu: *void)
def ps_unlock(mu: *void)
def ps_sdict_new(ksize: i64, vsize: i64, kstr: bool, vstr: bool) -> *PsSDict
def ps_sdict_len(d: *PsSDict) -> i64
# `key` points at the bytes of the key (a PsStr* when the key is a string).
def ps_sdict_put(ctx: *PsCtx, d: *PsSDict, key: const *void, val: const *void)
def ps_sdict_has(d: *PsSDict, key: const *void) -> bool
# copies the value OUT, into this context's heap when it is a string; raises
# when the key is absent, which is what `d[k]` does everywhere else (5.2)
def ps_sdict_get(ctx: *PsCtx, d: *PsSDict, key: const *void, out: *void, file: const *char, line: i32)
def ps_sdict_del(d: *PsSDict, key: const *void) -> bool
def ps_interval_new(ctx: *PsCtx, seconds: f64, file: const *char, line: i32) -> *PsTimer
def ps_timer_tick(ctx: *PsCtx, t: *PsTimer) -> *PsTask
def ps_box(ctx: *PsCtx, src: const *void, nbytes: usize, vt: const *void, isref: bool) -> *PsDyn
def ps_dyn_data(ctx: *PsCtx, d: *PsDyn) -> *void
# `xs.insert(i, v)` returns where to write; `remove_at` drops one element
def ps_list_has(ctx: *PsCtx, l: *PsList, needle: const *void, kind: i32) -> bool
# 108: definida nos três corpos de plataforma do multiplexador
# a descriptor about to be closed leaves the interest set: numbers are REUSED,
# and a stale entry made the next socket with that number never be watched
def ps_mux_forget(ctx: *PsCtx, fd: int)
def ps_mux_free(ctx: *PsCtx)
# 110: quantas threads de I/O o programa quer (antes da primeira operação)
def ps_pool_want(ctx: *PsCtx, n: i64, file: const *char, line: i32)
