"""Case mapping, the whole of it (bateria 89).

`upper()`/`lower()` used to map ASCII and leave everything else alone. What
made that fixable was not effort but MEASUREMENT: of 1_114_112 code points only
1423 have an uppercase different from themselves, and they fall into 678
contiguous ranges sharing one offset. With the 102 that map to more than one
character, and the two sets Final_Sigma needs, the whole table is 22 KB —
generated by `tools/gen_unicode_case.py` and embedded at compile time (63.1), so
it is read-only data with no initialisation and no allocation behind it.

`tests/oracle/py/unicase.psc` compares all 1.1 million mappings against Python
and agrees. What is pinned here is the handful that show WHY a table is needed:
no offset turns `ß` into `SS`.
"""

# a plain offset, which is all most of the table is
print("héllo wörld".upper())
print("ÀÉÎÕÜ".lower())
print("ΑΒΓΔΕ".lower(), "αβγδε".upper())
print("привет".upper(), "ПРИВЕТ".lower())

# one character in, MORE than one out — the half no offset can do
print("straße".upper())
print("ﬁxup".upper(), "ﬄ".upper())
print("ŉ".upper())

# TITLECASE characters, which are neither upper nor lower and map both ways
print("ǅungla".upper(), "ǅungla".lower())
print("ᾀ".upper(), "ᾈ".lower())

# FINAL SIGMA: the one conditional rule that is not about locale. `Σ` is `ς` at
# the end of a word and `σ` anywhere else, and a combining mark in between does
# not change which.
print("ΣΟΦΟΣ".lower())
print("ΣΟΦΟΣ ΑΝΘΡΩΠΟΣ".lower())
print("Σ".lower(), "ΑΣ".lower(), "ΑΣΑ".lower())
print("ΑΣ'".lower())

# and back up again: `ς` and `σ` both uppercase to `Σ`
print("σοφος".upper(), "ς".upper())

# what has no case travels through untouched
print("123 !@# 日本語 🙂".upper())
print(len("straße".upper()), len("straße"))
