"""DOCTEST: the example in the documentation is the example that runs.

The idea is Python's and it holds for the same reason: an example in a docstring
ages in silence. It looks right, nobody runs it, and one day somebody copies a
line that stopped working. Here it becomes a build edge like any other — if the
output changes, the build goes red.

The syntax is the one everybody already knows — three greater-than signs, the
expression, and the expected output on the next line. (The example below has one
sign fewer ON PURPOSE: this file is itself a module of a package, and a real
example here would become a test calling a function that does not exist. It is the
generator catching itself, which is the best sign that it works.)

    \"\"\"Adds two numbers.

    >> add(2, 3)
    5
    >> add(-1, 1)
    0
    \"\"\"

A `>>> expr` line is an EXPRESSION to print; the lines that follow, up to the
next `>>>` or to a blank line, are the expected output. There is no `...`
continuation and there are no blocks: a doctest that needs a `for` is no longer
documentation, it is a test — and tests have a home, which is `test/`.

**Where the docstrings come from: answer 5** (`plangc --api`), and not a second
reader of sources. It is the same canonical list `pforge doc` shows and the
repository's index carries, which means the doctest of a PUBLISHED package can be
run without having the source at hand.

**How it runs**: a module's examples become ONE generated program —
`from <pkg/mod.psc> import ...` with the module's public names, and one `print`
per example — which is compiled and run like any other test in the suite. The
comparison is the usual one: the whole output against the expected text.
"""
import path
import api as A

struct Example:
    expr: str
    expected: list<str>


def extract(doc: str) -> list<Example>:
    """A docstring's examples, in order."""
    out: list<Example> = []
    for line in doc.split("\n"):
        t = line.strip()
        if t.startswith(">>>"):
            out.append(Example(t[3:].strip(), []))
        elif len(out) > 0 and len(t) > 0:
            out[len(out) - 1].expected.append(t)
        elif len(t) == 0 and len(out) > 0 and len(out[len(out) - 1].expected) > 0:
            # a blank line CLOSES the expected output: without this, the
            # paragraph after the example became part of it
            out.append(Example("", []))
    clean: list<Example> = []
    for e in out:
        if len(e.expr) > 0:
            clean.append(e)
    return clean


struct Program:
    source: str         # the text of the generated program
    expected: str       # what it has to print
    count: int


def generate(mod: A.Api, imports: str) -> Program:
    """A module's program. `imports` is what goes in the `from ... import`:
    `<pkg/mod.psc>` for a package, or the name of the module next door."""
    names: list<str> = []
    examples: list<Example> = []
    for e in extract(mod.doc):
        examples.append(e)
    for s in mod.symbols:
        for e2 in extract(s.doc):
            examples.append(e2)
        # only SIMPLE names go into the `from ... import`: a method
        # (`Struct.method`) comes with its type, and an imported type brings its
        # methods with it
        if len(s.name) > 0 and "." not in s.name and s.name not in names:
            names.append(s.name)
    if len(examples) == 0:
        return Program("", "", 0)
    b = "# GENERATED by lib_doctest.psc from " + mod.path + " — do not edit.\n"
    if len(names) > 0:
        b += "from " + imports + " import " + ", ".join(sorted(names)) + "\n"
    b += "\n"
    exp = ""
    for e3 in examples:
        b += "print(" + e3.expr + ")\n"
        for ln in e3.expected:
            exp += ln + "\n"
    return Program(b, exp, len(examples))


def generate_ph(mod: A.Api, imports: str) -> Program:
    """The same, for a module in P: it comes in WHOLE (`import <pkg/mod.ph>`),
    because what crosses the boundary from it is decided by 45.5 and not by a list
    of names — and the names stay visible without a qualifier."""
    examples: list<Example> = []
    for e in extract(mod.doc):
        examples.append(e)
    for s in mod.symbols:
        for e2 in extract(s.doc):
            examples.append(e2)
    if len(examples) == 0:
        return Program("", "", 0)
    b = "# GENERATED by lib_doctest.psc from " + mod.path + " — do not edit.\n"
    b += "import " + imports + "\n\n"
    exp = ""
    for e3 in examples:
        b += "print(" + e3.expr + ")\n"
        for ln in e3.expected:
            exp += ln + "\n"
    return Program(b, exp, len(examples))
