"""`--emit-ninja`: the fat edge lowered into ninja text.

This is NOT a second engine: it is an EXPORT, and it exists for two concrete
reasons, neither of them being "in case pbuild is not good enough".

  * **bootstrapping on a clean machine.** Whoever clones this repository without
    `plangc` or `ppack` built can run `cc bootstrap/selfhost/*.c` and `ninja`, and
    come out with the whole compiler. The `build.ninja` committed at the root is
    the first build, and after it `ppack` takes over.
  * **compdb.** `ninja -t compdb` gives the `compile_commands.json` every language
    server and every `clang-tidy` in the world expects. Writing our own would be
    rewriting a format that already exists.

What the export does NOT promise is total fidelity, and the honest place to say
so is here:

  * ninja has no per-edge environment. Our `env=` REPLACES the environment, and
    that lowers into an explicit `env -i K=V ... command` in the command text —
    which works, but starts depending on an `env` in the PATH;
  * ninja has no per-edge directory. `cwd=` lowers into `sh -c 'cd D && exec
    ...'`, with the same kind of dependency;
  * ninja's `restat` compares MTIME and ours compares CONTENT (see
    `lib_log.psc`), so the exported pruning prunes LESS than ours. It recompiles
    more, never less: the error stays on the safe side;
  * ninja's command hash does not cover the environment; ours does. Swapping
    compilers through an environment variable is silent reuse there, and is not
    here.

ONE RULE PER EDGE, and that is a consequence of the model, not laziness: a fat
edge has no "rule" separate from the command — its command IS its command, built
by a pscript function that already knew everything. A `build.ninja` with a
thousand rules is bigger than one with ten, and is exactly as fast: ninja reads
the file once and this repository's `build.ninja` is tens of kB.

THE QUOTING IS GENERATED, and that is why it is correct. "What if the path has a
space in it" is the question that brings down every build system that assembles a
command line by concatenating text; here we know where every argument begins and
ends, because there never was a line — there was a vector.
"""
import lib_graph as G

# ---------- the two grammars ----------
# (SHELL quoting lives in `lib_graph`, because the export is not the only thing
# that needs it — see `G.sh_quote`)
# Ninja and the shell escape DIFFERENT things, and confusing them is the classic
# defect. `ninja_path` protects what ninja reads (its `$`, the `:` that separates
# outputs from the rule, the space that separates paths); `sh_quote` protects
# what the shell reads AFTERWARDS, inside the value of `command =`.
def ninja_path(s: str) -> str:
    out = ""
    for ch in s:
        if ch == "$":
            out += "$$"
        elif ch == " ":
            out += "$ "
        elif ch == ":":
            out += "$:"
        elif ch == "\n":
            out += "$\n"
        else:
            out += ch
    return out

def esc_command(s: str) -> str:
    """The command text still goes through ninja's reader, which eats `$`. A
    command line cannot contain a newline, and none of ours does."""
    out = ""
    for ch in s:
        if ch == "$":
            out += "$$"
        elif ch == "\n":
            out += " "
        else:
            out += ch
    return out

# ---------- one edge ----------
def cmdline(e: G.Edge) -> str:
    """The argument vector becomes ONE shell line — with `env -i` in front if the
    edge carried an environment, with a `cd` if it carried a directory, and with a
    redirection if it sent its output to a file."""
    parts: list<str> = []
    for a in e.argv:
        parts.append(G.sh_quote(a))
    line = " ".join(parts)
    if len(e.stdout_to) > 0:
        line += " > " + G.sh_quote(e.stdout_to)
    if len(e.env) > 0:
        # the SAME semantics as our `os.run`: it replaces, it does not merge.
        # `env -i` is what says that in shell, and the keys go in order so that
        # two `--emit-ninja` runs over the same graph give the same file
        ks: list<str> = []
        for k in e.env:
            ks.append(k)
        ks = sorted(ks)
        pre: list<str> = ["env", "-i"]
        for k2 in ks:
            pre.append(G.sh_quote(k2 + "=" + e.env[k2]))
        line = " ".join(pre) + " " + line
    if len(e.cwd) > 0:
        line = "cd " + G.sh_quote(e.cwd) + " && " + line
    if len(e.cwd) > 0 or len(e.env) > 0:
        line = "sh -c " + G.sh_quote(line)
    return esc_command(line)

private def paths(g: G.Graph, ids: list<int>) -> str:
    out: list<str> = []
    for i in ids:
        out.append(ninja_path(g.nodes[i].p))
    return " ".join(out)

# ---------- the file ----------
def emit(g: G.Graph) -> str:
    out = "# generated by `ppack ninja` — do NOT edit by hand.\n"
    out += "#\n"
    out += "# This file is the BOOTSTRAP: on a machine with no `ppack` built,\n"
    out += "#   cc -O2 -o plangc bootstrap/selfhost/*.c && ninja\n"
    out += "# builds everything. After that `ppack` is in charge, and it reads\n"
    out += "# the descriptor in pscript, not this file.\n"
    out += "#\n"
    out += "# The export is FAITHFUL in what it builds and CONSERVATIVE in what it\n"
    out += "# prunes: `restat` here compares dates and ours compares content, so\n"
    out += "# this file recompiles more, never less.\n"
    out += "\n"
    out += "ninja_required_version = 1.5\n"
    out += "\n"
    has_console = False
    for e0 in g.edges:
        if e0.pool == "console":
            has_console = True
    if has_console:
        out += "# ninja's `pool console` already exists and means exactly what ours\n"
        out += "# means: one edge at a time, talking to the terminal.\n"
        out += "\n"
    for e in g.edges:
        name = "e" + str(e.id)
        out += "rule " + name + "\n"
        out += "  command = " + cmdline(e) + "\n"
        if len(e.desc) > 0:
            out += "  description = " + esc_command(e.desc) + "\n"
        if len(e.depfile) > 0:
            out += "  depfile = " + ninja_path(e.depfile) + "\n"
            out += "  deps = gcc\n"
        if e.restat:
            out += "  restat = 1\n"
        if e.generator:
            out += "  generator = 1\n"
        if e.pool == "console":
            out += "  pool = console\n"
        out += "\n"
        line = "build " + paths(g, e.outs)
        if len(e.out_implicit) > 0:
            line += " | " + paths(g, e.out_implicit)
        line += ": " + name
        if len(e.ins) > 0:
            line += " " + paths(g, e.ins)
        if len(e.implicit) > 0:
            line += " | " + paths(g, e.implicit)
        if len(e.order) > 0:
            line += " || " + paths(g, e.order)
        out += line + "\n\n"
    if len(g.default_targets) > 0:
        ds: list<str> = []
        for d in g.default_targets:
            ds.append(ninja_path(d))
        out += "default " + " ".join(ds) + "\n"
    return out
